name: Dailies
version: ${project.version}
main: devlaunchers.dailies.Dailies
api-version: 1.16
commands:
  saveInventory:
    description: Saves a players current inventory
    usage: /saveInventory
    permission: dailies.saveInventory
  loadInventory:
    description: Loads a players saved inventory
    usage: /loadInventory
    permission: dailies.loadInventory
  daily:
    description: Summons a daily NPC which guides players to their own daily world
    usage: /daily
    permission: dailies.daily

